version: "3.5"
services:
  postgres:
    image: postgres:14.5
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_MULTIPLE_DATABASES=k_rust_post
      - POSTGRES_USER=k-rust
      - POSTGRES_PASSWORD=abcabc123
    ports:
      - '5433:5432'
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"

    command: "--http_port 8222 -js"
    networks: ["nats"]
  # nats-1:
  #   image: nats
  #   command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
  #   networks: ["nats"]
  #   depends_on: ["nats"]
  # nats-2:
  #   image: nats
  #   command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
  #   networks: ["nats"]
  #   depends_on: ["nats"]
networks:
  nats:
    name: nats